# src/main/resources/application.yml

# Server Configuration
server:
  port: 8080

# Database Configuration (DEFAULT PROFILE - H2 ONLY)
spring:
  datasource:
    # REMOVE 'DB_MODE=PostgreSQL' from the URL
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1 # <-- MODIFIED LINE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    # Keep PostgreSQLDialect if your entities use PostgreSQL-specific features like UUID
    # or array types. Otherwise, you can change this to H2Dialect.
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Keep PostgreSQLDialect if your entities use PostgreSQL-specific features.
        # Otherwise, you can change this to H2Dialect.
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: true # Enable H2 console for easy viewing at /h2-console

# JWT Configuration
jwt:
  secret: your-super-secret-jwt-key-for-health-first-server-2025
  expiration: 3600
  issuer: health-first-server

# Logging
logging:
  level:
    com.healthfirst.server: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    disable-swagger-default-url: true
  packages-to-scan: com.healthfirst.server.controller

---
# Test Profile Configuration (ALSO MODIFY THIS SECTION!)
spring:
  config:
    activate:
      on-profile: test
  datasource:
    # REMOVE 'DB_MODE=PostgreSQL' from the URL
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1 # <-- MODIFIED LINE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Keep this as explained above


